### ISSUE TITLE
Possible to pull variable names out of the parser?

### ISSUE THREAD

**Issue by DelvarWorld** [cimaron/glsl2js#36]
When I look at the output of parsed state, I see `state.symbols.table` - but this only seems to have keywords for the language, like `dot`, `gl_FragColor`, `main`, etc. It doesn't have variables I define in the code like `vec2 position;`. In analyzing the tree I need to see the scope of the variable defined. Does this information automatically come out of jison?

**Comment by AndrewRayCode** [comment]
I'm able to get these myself from just walking the tree, so I don't need this as core functionality
