### ISSUE TITLE
Directives improperly replaced in source when names overlap

### ISSUE THREAD

**Issue by DelvarWorld** [cimaron/glsl2js#45]
I have a shader that has these defines:

    #define K 0.14285
    #define Ko 0.4285

When I try to parse the shader, I get this error:

    Uncaught Parse error on line 34:
    ...57) - 0.14285o;	vec3 oy = mod(fl
    ----------------^

This is the input line:

	vec3 ox = fract(p*K) - Ko;

You can see it appears to be thinking that `Ko` is actually `K` then identifier `o`, so it errors.

Additionally, is it possible to prevent inlining of define statements in the parsed AST?

**Comment by cimaron** [comment]
Merged.

**Comment by cimaron** [comment]
I think, in order to do what you're asking would require turning off the directives part of the preprocessor. But then, that would leave directives in place, and the parser is going to barf on those.
