### ISSUE TITLE
Extra semicolons are parsed as ";" instead of nodes

### ISSUE THREAD

**Issue by DelvarWorld** [cimaron/glsl2js#49]
Extra semocolons, as in:

    gl_FragColor = cubeColor;;

Get parsed into the tree as the string `";"` instead of an actual node type. I'm not sure what an extra semicolon *should* parse as. Maybe an emptystatement node? There's a few mentions of "empty" in the glsl grammar spec, but I don't know if those apply here.

**Comment by AndrewRayCode** [comment]
You are a machine
